### ISSUE TITLE
 local project deployment error

### ISSUE THREAD

**Issue by hatem-benmansour-lmfr** [adeo/mozaic-design-system#591] opened 2020-06-24 15:09 UTC
# 🐞 Styleguide bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description
Hello , 
I followed the doc in order to launch mozaic design system unfortunately by launching the command "yarn deve" and especially the task "mozaic-tokens-build" I had two errors:
- the script can't find node  "mozaic-tokens-build
**"/ usr / bin / env: "node \ r": No such file or folder "** and I corrected it by changing" #! / usr / bin / env node "in build.js
- No permission on the build.js file **"/ bin / sh: 1: mozaic-tokens-build: Permission denied
error Command failed with exit code 126. "** 
knowing that I have assigned the correct rights to the build.js file

Ubunut 18.04.4 LTS
node version: v11.15.0
yarn version: 1.22.4

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment

**Styleguide Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by tiloyi** [comment] 2021-03-08 12:52
I close this ticket because unfortunately, the problem is old, and we didn't manage to reproduce the bug.

We will reopen this ticket in case other people are confronted to us with this kind of problem.

**Closed by tiloyi** 2021-03-08 12:52 UTC
Labels: fix
