### ISSUE TITLE
Breadcrumb component style

### ISSUE THREAD

**Issue by florencemcd** [adeo/mozaic-design-system#1224] opened 2022-10-10 15:09 UTC
### I want to propose an evolution/improvement on

Component

### Description

Hello,
We have an issue on the breadcrumb component :
Why is there a padding-left set on [.mc-breadcrumb](https://github.com/adeo/mozaic-design-system/blob/master/packages/styles/components/_c.breadcrumb.scss) depending the breakpoint ? 

We would like to align the breadcrumb with the .ml-container, but because of this padding-left we can't. 
The breadcrumb currently : 
![Capture d’écran 2022-10-10 à 17 14 09](https://user-images.githubusercontent.com/52403506/194899600-6c2a0785-d4b7-469c-82c4-ed460ff28571.png)

When we add .ml-container class , the breadcrumb is not align on the container : 
![Capture d’écran 2022-10-10 à 15 54 37](https://user-images.githubusercontent.com/52403506/194896959-86aa0475-7533-449a-b3bc-7b3d53b8a004.png)

Expected result : 
![Capture d’écran 2022-10-10 à 15 54 54](https://user-images.githubusercontent.com/52403506/194896998-ffb7d680-8700-4a9f-b522-16b48ca74c57.png)

### Describe the solution you would like

Can we remove the padding-left in mozaic-design-system and add the .ml-container class directly on the macro breadcrumb in breadcrumb-module ? If it's not possible we will have to override the style from Mozaic design system to align the breadcrumb with the content.

### Additional comments

@MaximeDecourtray

**Comment by tiloyi** [comment] 2022-10-11 16:30
Hi @florencemcd , Hi @MaximeDecourtray ,
This component was designed like this several years ago.

We have decided to review this behaviour a few months ago, and the correction has already been made via the following PR:
=> https://github.com/adeo/mozaic-design-system/pull/1098

Since removing this padding would be a breaking visual change in many applications/projects that use this component; this fix will only be released in the [next ](https://github.com/adeo/mozaic-design-system/milestone/2) major version of Mozaic; which will arrive by the end of this month.

I am therefore closing this issue, as the subject has already been dealt with.

Do not hesitate to reopen it if you have other requests related to this.

**Closed by tiloyi** 2022-10-11 16:30 UTC
Labels: :rocket: feat

**Comment by florencemcd** [comment] 2022-10-12 09:29
> Hi @florencemcd , Hi @MaximeDecourtray , This component was designed like this several years ago.
> 
> We have decided to review this behaviour a few months ago, and the correction has already been made via the following PR: => #1098
> 
> Since removing this padding would be a breaking change in many applications/projects that use this component; this feature will only be released in the [next ](https://github.com/adeo/mozaic-design-system/milestone/2) major version of Mozaic; which will arrive by the end of this month.
> 
> I am therefore closing this issue, as the subject has already been dealt with.
> 
> Do not hesitate to reopen it if you have other requests related to this.

Hi Trésor, thank you for your feedback it's ok for me, I will let the team know about this new change in the next major release 👍🏻
