### ISSUE TITLE
Performance issues on DatatableV2 (Pagination)

### ISSUE THREAD

**Issue by vqoph** [adeo/mozaic-design-system#1497] opened 2023-09-27 12:56 UTC
### I am opening an issue for

Component

### Package version

@mozaic-ds/vue-3

### Description

When using the datatableV2 with a lot of pages (more than 1000) we can encounter slowing of datatable refresh and interactions (especially with devtools) 

I suspect the Pagination component, that generate the totality of pages as option marks on the select, this cause browser calculation that can cause this performance issue. 

![image](https://github.com/adeo/mozaic-design-system/assets/5341141/11c2aa15-227b-4a99-a7af-3e5896222295)

a possible solution is to generate just a partial list of page in the select field. 

### To Reproduce

Load a datatableV2 with quick responding xhr and a lot of pages (more than 1000)

### Is this a regression?

- [ ] Yes
- [X] No
- [ ] I don't know

**Comment by tiloyi** [comment] 2024-02-08 08:42
Hi @vqoph ,
Thank you for your request.

The performance problem you are experiencing is caused by the large number of options created by the browser in the Select pagination.

To fix this you just need to use the `showPartialPages` prop.

This will display only the 3 pages preceding & following the current page.

So I'm closing this exit.
Don't hesitate to open it again if you need to.

**Closed by tiloyi** 2024-02-08 08:42 UTC
Labels: :x: wont fix
