### ISSUE TITLE
Allow using 16px icon in buttons

### ISSUE THREAD

**Issue by MatthieuLepers** [adeo/mozaic-design-system#968] opened 2021-12-03 12:59 UTC
# 🚀 Pattern addition proposal

### Description
Hello, i want to use icon-only button with 16px sized icon, actually the minimum size of any icon (text & icon button and icon-only button) is forced to 24px
Also, in linked screenshots, i override border-styled button into shadow-styled button to make it look like Fig. 03 which is not using mozaic button

So, my proposals are the following :
- Allow 16px sized icon to be used in icon-only button without forcing them become 24px sized icon
- Add a style variant in additions to solid and bordered : shadowed

**Anything else relevant?**
Environment : https://leroymerlin-team-media-dev-frlm-uat1.nprd-02-a9ef.priv.manawa.adeo.cloud/ 
Team : Smart content
Page : Homepage
Screenshots :
Fig. 01, homepage
![Fig. 01](https://user-images.githubusercontent.com/14954276/144604977-9a81738e-3cf1-446c-8d5a-78e4ba4150bf.png)
Fig. 02, homepage
![Fig. 02](https://user-images.githubusercontent.com/14954276/144604971-65d0e065-5b43-4e0b-9a3d-f1be69e39bef.png)
Fig. 03, homepage (same as prod env)
![Fig. 03](https://user-images.githubusercontent.com/14954276/144605640-d2dea7d3-b9b9-4d60-816b-a90e47b7a992.png)

**Comment by caqueste** [comment] 2021-12-10 16:55
Hello, @MatthieuLepers 👋
Thanks for the issue.
Adding a variant with the 16px icon is not a good idea, the problem is mainly caused by the design of the icon.
We'll add a new arrow icon (smaller) in 24px 😉 

For this case: ```Add a style variant in additions to solid and bordered : shadowed```
Please, do not override the button. This button is a legacy of old buttons, they aren't accessible and up to date with the style of the other components. Just replace it with the bordered-neutral button.

**Comment by tiloyi** [comment] 2022-03-16 05:38
Hi @caqueste , Hi @MatthieuLepers ,
Is this PR still relevant? Or can we close it?

**Comment by tiloyi** [comment] 2022-03-30 20:54
Not having any answers from you guys; I'm closing this issue. Feel free to reopen it if you need to.

**Closed by tiloyi** 2022-03-30 20:54 UTC
